version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cts-label
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:9.3.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: label_new
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_PASSWORD: your_password
      MYSQL_USER: laravel_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel_network

  node:
    image: node:18
    container_name: node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - laravel_network
      
networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata: