version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cts-label
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:9.3.0
    container_name: db
    restart: unless-stopped
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: label_new
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

  node:
    image: node:18
    container_name: node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - laravel_network
      
networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata: